<a href="https://colab.research.google.com/github/22922511/MachineLearningResource/blob/main/Simple%20Linear%20Regression%20%7C%20Mathematical%20Formulation/48Simple%20Linear%20Regression%20%7C%20Mathematical%20Formulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [104]:
class LinearRegression:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self,X_train,y_train):

        num = 0
        den = 0

        for i in range(X_train.shape[0]):

            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))

        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)

    def predict(self,X_test):

        print(X_test)

        return self.m * X_test + self.b

In [105]:
df = pd.read_csv("/content/placement (2).csv", index_col=None)


In [121]:
x=df.iloc[:,0:1].values
y=df.iloc[:,-1].values

In [122]:
from sklearn.model_selection import train_test_split

In [123]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [124]:
lr=LinearRegression()
lr.fit(x_train,y_train)


[0.55490089]
[-0.88137372]


In [125]:
lr.predict(x_test)-y_test

[[5.94]
 [5.64]
 [8.44]
 [6.19]
 [7.04]
 [6.5 ]
 [6.26]
 [7.56]
 [5.32]
 [5.88]
 [8.01]
 [7.11]
 [6.1 ]
 [6.42]
 [6.1 ]
 [8.94]
 [7.38]
 [7.33]
 [6.22]
 [7.12]
 [8.31]
 [6.85]
 [4.79]
 [5.23]
 [5.95]
 [6.47]
 [7.91]
 [8.71]
 [6.63]
 [6.6 ]
 [8.99]
 [6.66]
 [6.92]
 [6.89]
 [7.28]
 [7.21]
 [6.86]
 [7.3 ]
 [5.12]
 [6.35]]


array([[ 0.17473757,  0.31473757, -1.61526243, ..., -0.91526243,
         0.40473757, -0.31526243],
       [ 0.0082673 ,  0.1482673 , -1.7817327 , ..., -1.0817327 ,
         0.2382673 , -0.4817327 ],
       [ 1.5619898 ,  1.7019898 , -0.2280102 , ...,  0.4719898 ,
         1.7919898 ,  1.0719898 ],
       ...,
       [ 0.92940278,  1.06940278, -0.86059722, ..., -0.16059722,
         1.15940278,  0.43940278],
       [-0.28028116, -0.14028116, -2.07028116, ..., -1.37028116,
        -0.05028116, -0.77028116],
       [ 0.40224693,  0.54224693, -1.38775307, ..., -0.68775307,
         0.63224693, -0.08775307]])

In [115]:
y_test

array([3.67, 2.61, 2.31, 2.25, 3.13, 2.57, 2.59, 2.92, 2.35, 3.14, 3.89,
       2.99, 3.34, 2.48, 4.06, 3.67, 1.48, 3.16, 2.21, 3.33, 2.17, 3.74,
       2.93, 3.23, 2.84, 4.09, 2.66, 4.1 , 3.76, 3.09, 2.37, 2.72, 2.43,
       2.51, 1.86, 1.37, 3.02, 3.42, 2.61, 1.73])